before_script:
    - curl -sSL https://get.docker.com/ | sh
    - id 
    - usermod -aG docker root
    - docker version
    - service docker start

build-monls:
    script:
        - docker run hello-world 
        - docker build .

